<?php

$tables = array(
    after_invent => array(//name,proto,server
        array(form => 'text', caption => 'Аккоунт', status => 'X', name => 'name', value => ''),
        array(form => 'text', caption => 'Протокол', status => 'X', name => 'proto', value => ''),
        array(form => 'text', caption => 'Сервер', status => 'X', name => 'proto', value => ''),
    ),
    params_pages_ids => array(
        array(form => 'select', caption => 'Тип VPN', first_val => 'no', status => 'X', name => 'type_id', value => '',
            data => array('vars_db::__table', array('table' => 'types', 'order' => 'id'))),
        array(form => 'select', caption => 'Протокол', first_val => 'no', status => 'X', name => 'protocol_id', value => '',
            data => array('vars_db::__table', array('table' => 'protocols'))),
        array(form => 'select_simple', caption => 'OS', status => '0', name => 'os', value => '', values => array('win' => 'Win', 'mac' => 'Mac')),
        //array(form => 'select_simple', caption => 'Portable', status => '0', name => 'portable', value => '', values => array(0=>'',1 =>'isPortabl')),
        array(form => 'checkbox', caption => 'is Portable', status => '0', name => 'portable', value => '1', checked => 1),
        array(form => 'select',
            caption => 'Страничка',
            status => '0',
            name => 'page_id',
            first_val => '',
            value => '',
            data => array('vars_db::__table', array('table' => $pref . 'pages', 'order' => 'id'))
        ),
        array(form => 'text', caption => 'Якорь', status => 'X', name => 'yakor', value => ''),
    ),
    orders_params => array(
        array(form => 'select', caption => 'Заказчик', first_val => 'no', status => '0', is_disabled => 1, name => 'user_id', value => '',
            data => array('vars_db::__table', array('table' => 'users'))),
        array(form => 'select', caption => 'Тип VPN', first_val => '', status => '0', is_disabled => 1, name => 'type_id', value => ($action == 'add') ? '1' : '',
            data => array('vars_db::__table', array('table' => 'types', 'order' => 'id'))),
        array(form => 'select', caption => 'Протокол', first_val => 'no', status => '0', is_disabled => 1, name => 'protocol_id', value => '',
            data => array('vars_db::__table', array('table' => 'protocols', 'order' => 'name desc'))),
        array(form => 'date_form', caption => 'Дата начала', format => 'dd.mm.yy', status => '0', is_disabled => 1, name => 'datetime_begin', value => ($action == 'add') ? date("Y-m-d") : ''),
        array(form => 'date_form', caption => 'Дата конца', format => 'dd.mm.yy', status => '0', is_disabled => 1, name => 'datetime_expire', value => ''),
        array(form => 'select', caption => 'Период', first_val => '', status => '0', is_disabled => 1, name => 'period_id', value => '2',
            data => array('vars_db::__table', array('table' => 'periods', 'order' => 'id'))),
        array(form => 'select',
            caption => 'Сервера',
            first_val => 'no',
            status => '0',
            sel_field => 'id, name',
            name => 'order_server_ids', value => array(),
            get_value => array('vars_db::__selected_ids', array('table' => 'order_server_ids', 'field' => 'serverID', 'where' => (($id) ? 'orderID=' . $id : ''))),
            data => array('vars_db::__table', array('table' => 'servers', 'where' => ($action == 'add') ? ' idmultidouble="" and iddouble=""' : ''))),
        array(form => 'select', caption => 'Статус', status => '0', first_val => 'no', is_disabled => 1, name => 'action_id', value => '',
            data => array('vars_db::__table', array('table' => 'actions', 'order' => 'id'))),
        array(form => 'text', caption => 'Цена($)', status => '0', is_disabled => 1, name => 'price', value => ''),
        array(form => 'checkbox', caption => 'is Portable', status => '0', is_disabled => 1, name => 'portable', value => 1, checked => 1),
        array(form => 'select_simple', caption => 'OS', status => '0', is_disabled => 1, name => 'os', value => '', values => array('win' => 'Win', 'mac' => 'Mac')),
        array(form => 'textarea', caption => 'Заметки', status => '0', is_disabled => 1, name => 'notes', value => ''),
    ),
    pages => array(
        array(form => 'text', caption => 'Заголовок', status => 'X', name => 'name', value => ''),
        // array(form=>'text',		caption=>'Url',			status=>'X',     name=>'url',        value=>''),
        //array(form => 'text', caption => 'Слог', status => 'X', name => 'slogan', value => ''),
        //array(form => 'textarea', caption => 'Контент странички слева', status => '0', name => 'content_page_left', value => $shablon_page, css => 'tinymce'),
        array(form => 'textarea', caption => 'Контент странички', status => '0', name => 'content_page', value => '', css => 'tinymce'),
        array(form => 'text', caption => 'Title', status => '0', name => 'title', value => ''),
        array(form => 'text', caption => 'Description', status => '0', name => 'description', value => ''),
        array(form => 'text', caption => 'KeyWords', status => '0', name => 'keywords', value => ''),
    ),
    menu => array(
        array(form => 'text', caption => 'Название', status => '0', name => 'name', value => ''),
        array(form => 'select',
            caption => 'Родитель',
            status => '0',
            name => 'pid',
            first_val => '',
            value => '',
            data => array('vars_db::__table', array('table' => $pref . 'menu', 'order' => 'id'))
        ),
        array(form => 'select',
            caption => 'Страничка',
            status => '0',
            name => 'pages_id',
            first_val => '',
            value => '',
            data => array('vars_db::__table', array('table' => $pref . 'pages', 'order' => 'id'))
        ),
        array(form => 'text', caption => 'Url', status => '0', name => 'url', value => ''),
        array(form => 'text', caption => 'Сортировка', status => '0', name => 'sort', value => '0'),
        array(form => 'checkbox', caption => 'Правый блок сайта', status => '0', name => 'right_part', value => 1, checked => 1),
        array(form => 'checkbox', caption => 'Статус', status => '0', name => 'status', value => 1, checked => 1)
    ),
    news => array(
        //  array(form => 'select', caption => 'Специалист',                status => 'X',  name => 'spec_id', value => '', table => 'spec'),
        array(form => 'date_form', caption => 'Дата', status => 'X', name => 'date', format => 'dd.mm.yy', value => '',),
        array(form => 'text', caption => 'Заголовок ', status => 'X', name => 'name', value => ''),
        array(form => 'textarea', caption => 'Содержание', status => '0', name => 'content_page', value => '', css => 'tinymce'),
        array(form => 'file', caption => 'Файл  катринки', status => '0', name => 'img', value => '',
            upload_mode_save => 2, acceptable_file_types => 'gif|jpg|jpeg|png',
            upload_max_size => 5190000000,
            upload_maxx => 5600,
            upload_maxy => 5200,
            img_x => 150, img_y => 150,
            preview_x => 150, preview_x => 100,
            crop_max => 1,
            crop_small => 1,
            path_img => commonConsts::path_img_admin . '/news/',
        // upload_add_img=>array('src'=>commonConsts::path_img_admin.'/watermark.png')
        ),
        array(form => 'checkbox', caption => 'Статус', status => '0', name => 'status', value => 1, checked => 1),
    //array(form=>'text',             caption=>'Title',		status=>'0',    name=>'title',      value=>''),
    //array(form=>'text',             caption=>'Description',		status=>'0',    name=>'description',value=>''),
    //array(form=>'text',             caption=>'KeyWords',		status=>'0',    name=>'keywords',   value=>''),
    ),
    faq => array(
        array(form => 'select',
            caption => 'Группа',
            status => 'X',
            name => 'group_id',
            value => '',
            data => array('vars_db::__table', array('table' => $pref . 'faq_group', 'order' => 'id'))
        ),
        array(form => 'text', caption => 'Вопрос', status => 'X', name => 'name', value => '', css => ''),
        array(form => 'textarea', caption => 'Ответ', status => '0', name => 'name_a', value => '', css => 'tinymce'),
        array(form => 'checkbox', caption => 'Статус', status => '0', name => 'status', value => 1, checked => 1),
        array(form => 'checkbox', caption => 'На главной', status => '0', name => 'is_front', value => 1, checked => 1),
        array(form => 'text', caption => 'Вес', status => '0', name => 'weight', value => ''),
    //array(form=>'text',             caption=>'Title',		status=>'0',    name=>'title',      value=>''),
    //array(form=>'text',             caption=>'Description',		status=>'0',    name=>'description',value=>''),
    //array(form=>'text',             caption=>'KeyWords',		status=>'0',    name=>'keywords',   value=>''),
    ),
    faq_group => array(
        array(form => 'text', caption => 'Название группы', status => 'X', name => 'name', value => ''),
    ),
    users => array(
        array(form => 'text', caption => 'Логин ', status => 'X', name => 'login', value => ''),
        array(form => 'text', caption => 'Пароль ', status => '0', name => 'passwd', is_disabled => 1, value => ''),
        array(form => 'text', caption => 'Имя', status => 'X', name => 'name', value => ''),
        array(form => 'text', caption => 'E-mail', status => 'X', name => 'email', value => ''),
        array(form => 'text', caption => 'ICQ', status => '0', name => 'icq', value => ''),
        array(form => 'text', caption => 'Jabber', status => '0', name => 'jabber', value => ''),
        array(form => 'text', caption => 'Skype', status => '0', name => 'skype', value => ''),
        array(form => 'textarea', caption => 'Заметки', status => '0', name => 'notes', value => ''),
        array(form => 'checkbox', caption => 'Статус', status => '0', name => 'status', value => 1, checked => 1),
        //array(form => 'date_form', caption => 'Дата регистрации', status => '0', name => 'date_reg', value => ''),
        array(form => 'select_simple', caption => 'Тип пользователя', status => '0', name => 'tip_user', values => array('user' => 'user', 'operator' => 'operator', 'admin' => 'admin'), value => $_POST['tip_user']),
        array(form => 'select_simple', caption => 'Способ рассылки сообщений', status => '0', name => 'note_method', values => array('email' => 'email', 'jabber' => 'jabber', 'icq' => 'icq'), value => $_POST['tip_user']),
            array(form => 'select', caption => 'Группа', status => 'X', first_val => 'no', name => 'group_id', value => '',
            data => array('vars_db::__table', array('table' => 'user_groups', 'order' => 'id'))),
    ),
    accounts => array(
        array(form => 'text', caption => 'Логин ', status => 'X', name => 'name', value => ''),
        array(form => 'text', caption => 'Пароль ', status => 'X', name => 'pass', value => ''),
        array(form => 'checkbox', caption => 'Статус', status => '0', name => 'status', value => 1, checked => 1),
    ),
    countries => array(
        array(form => 'text', caption => 'Название', status => 'X', name => 'name', value => ''),
        array(form => 'text', caption => 'Сокращение', status => 'X', name => 'shot_name', value => ''),
        array(form => 'checkbox', caption => 'Статус', status => '0', name => 'status', value => 1, checked => 1),
    ),
    protocols => array(
        array(form => 'text', caption => 'Название', status => 'X', name => 'name', value => ''),
        array(form => 'checkbox', caption => 'Статус', status => '0', name => 'status', value => 1, checked => 1),
    ),
    periods => array(
        array(form => 'text', caption => 'Для пользователя', status => 'X', name => 'name', value => ''),
        array(form => 'text', caption => 'Для mysql', status => 'X', name => 'for_sql', value => ''),
        array(form => 'checkbox', caption => 'Статус', status => '0', name => 'status', value => 1, checked => 1),
    ),
    servers => array(
        array(form => 'text', caption => 'Номер сервера ', status => 'X', name => 'num_ser', value => ''),
        array(form => 'text', caption => 'Название ', status => 'X', name => 'name', value => ''),
        array(form => 'text', caption => 'ID для Дабла ', status => '0', name => 'iddouble', value => ''),
        array(form => 'text', caption => 'ID для мультиДабла(папка) ', status => '0', name => 'idmultidouble', value => ''),
        array(form => 'text', caption => 'IP', status => '0', name => 'ip', value => ''),
        array(form => 'text', caption => 'Hostname ', status => 'X', name => 'hostname', value => ''),
        array(form => 'select', caption => 'DNS1', first_val => '', status => 'X', name => 'dns1_id', value => '1',
            data => array('vars_db::__table', array('table' => 'dns'))
        ),
        array(form => 'select', caption => 'DNS2', first_val => '', status => 'X', name => 'dns2_id', value => '1',
            data => array('vars_db::__table', array('table' => 'dns'))
        ),
        array(form => 'text', caption => 'Порт', status => 'X', name => 'port', value => ''),
        array(form => 'checkbox', caption => 'Участие в мульти аккаунте', status => '0', name => 'part_multi', value => 1, checked => 1),
        array(form => 'select', caption => 'Страна', first_val => '', status => 'X', name => 'country_id', value => '1',
            data => array('vars_db::__table', array('table' => 'countries'))),
        array(form => 'text', caption => 'Hoster', status => 'X', name => 'hoster', value => ''),
        array(form => 'text', caption => 'Email', status => 'X', name => 'emails', value => ''),
        array(form => 'text', caption => 'Способ оплаты сервера', status => 'X', name => 'payment', value => ''),
        array(form => 'date_form', caption => 'Дата наччала аренды', status => '0', name => 'date_begin', format => 'dd.mm.yy', value => ''),
        array(form => 'date_form', caption => 'Дата конца аренды', status => '0', name => 'date_expire', format => 'dd.mm.yy', value => ''),
        array(form => 'textarea', caption => 'Содержание', status => '0', name => 'comments', value => '', css => 'tinymce'),
        array(form => 'checkbox', caption => 'Статус', status => '0', name => 'status', value => 1, checked => 1),
    ),
    prices => array(
        array(form => 'select', caption => 'Период', first_val => '', status => 'X', name => 'period_id', value => '',
            data => array('vars_db::__table', array('table' => 'periods', 'order' => 'id'))),
        array(form => 'select', caption => 'Тип VPN', first_val => 'no', status => 'X', name => 'type_id', value => '',
            data => array('vars_db::__table', array('table' => 'types', 'order' => 'id'))),
        array(form => 'select', caption => 'Страна(ы)', first_val => 'no', status => 'X', name => 'price_country_ids', value => array(),
            get_value => array('vars_db::__selected_ids', array('table' => 'price_country_ids', 'field' => 'countryID', 'where' => ($id) ? 'priceID=' . $id : '')),
            data => array('vars_db::__table', array('table' => 'countries', 'order' => 'id'))),
        array(form => 'text', caption => 'Цена($)', status => '0', name => 'name', value => ''),
        //  array(form => 'checkbox', caption => 'Portable (include)', status => '0', name => 'portable_include', value => 1, checked => 1),
        array(form => 'text', caption => 'Цена для portable', status => '0', name => 'portable_price', value => ''),
        array(form => 'checkbox', caption => 'Статус', status => '0', name => 'status', value => 1, checked => 1),
        array(form => 'text', caption => 'Сортировка', status => '0', name => 'sort', value => 1),
    ),
    types => array(
        array(form => 'text', caption => 'Тип VPN', status => 'X', name => 'name', value => ''),
        array(form => 'select', caption => 'Протокол(ы)', first_val => 'no', status => 'X', name => 'type_protocol_ids', value => array(),
            get_value => array('vars_db::__selected_ids', array('table' => 'type_protocol_ids', 'field' => 'protocolID', 'where' => ($id) ? 'typeID=' . $id : '')),
            data => array('vars_db::__table', array('table' => 'protocols'))),
        array(form => 'checkbox', caption => 'Статус', status => '0', name => 'status', value => 1, checked => 1)
    ),
    actions => array(
        array(form => 'text', caption => 'Статус ордера', status => 'X', name => 'name', value => ''),
    ),
    dns => array(
        array(form => 'text', caption => 'dsn', status => 'X', name => 'name', value => ''),
    ),
//      `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
//  `type_id` int(3) DEFAULT NULL,
//  `action_id` int(11) DEFAULT '1',
//  `protocol_id` int(11) DEFAULT NULL,
//  `command_line` varchar(255) DEFAULT NULL,
    commads => array(
        array(form => 'select', caption => 'Тип VPN', first_val => 'no', status => 'X', name => 'type_id', value => '',
            data => array('vars_db::__table', array('table' => 'types', 'order' => 'id'))),
        array(form => 'select', caption => 'Действие', status => 'X', sel_field => 'id, action', first_val => 'no', name => 'action_id', value => '',
            data => array('vars_db::__table', array('table' => 'actions', 'order' => 'id'))),
        array(form => 'select', caption => 'Протокол', first_val => 'no', status => 'X', name => 'protocol_id', value => '',
            data => array('vars_db::__table', array('table' => 'protocols'))),
        array(form => 'text', caption => 'Командная строка', status => 'X', name => 'name', value => ''),
    ),
    config_rules => array(
        array(form => 'select', caption => 'Тип VPN', first_val => 'no', status => 'X', name => 'type_id', value => '',
            data => array('vars_db::__table', array('table' => 'types', 'order' => 'id'))),
        array(form => 'select', caption => 'Протокол', first_val => 'no', status => 'X', name => 'protocol_id', value => '',
            data => array('vars_db::__table', array('table' => 'protocols'))),
        array(form => 'select_simple', caption => 'OS', status => '0', name => 'os', value => '', values => array('win' => 'Win', 'mac' => 'Mac')),
        //array(form => 'select_simple', caption => 'Portable', status => '0', name => 'portable', value => '', values => array(0=>'',1 =>'isPortabl')),
        array(form => 'checkbox', caption => 'is Portable', status => '0', name => 'portable', value => '1', checked => 1),
        array(form => 'text', caption => 'Папка для конфига', status => '0', name => 'config_folder', value => ''),
        array(form => 'text', caption => 'Папка для дополнительных файлов', status => '0', name => 'add_files_folder', value => ''),
        array(form => 'text', caption => 'Имя файла конфига', status => 'X', name => 'ext_conf_file', value => ''),
        //array(form => 'text', caption => 'Название файла с паролем/логином', status => '0', name => 'aname', value => 'pass.txt'),
        array(form => 'textarea', caption => 'Шаблон для конфига', status => '0', name => 'config_temlplate', value => '', css => ''),
    ),
    //id, user_id,  num_order,datetime_begin, datetime_expire, period_id
    //type_id,protocol_id, country_id, server_id, 
    // price, ammount, portable,action_id
    orders => array(
        array(form => 'select', caption => 'Заказчик', first_val => 'no', status => 'X', name => 'user_id', value => '',
            data => array('vars_db::__table', array('table' => 'users'))),
        array(form => 'select', caption => 'Тип VPN', first_val => '', status => 'X', name => 'type_id', value => ($action == 'add') ? '1' : '',
            data => array('vars_db::__table', array('table' => 'types', 'order' => 'id'))),
        array(form => 'select', caption => 'Протокол', first_val => 'no', status => 'X', name => 'protocol_id', value => '',
            data => array('vars_db::__table', array('table' => 'protocols', 'order' => 'name desc'))),
        array(form => 'text', caption => 'Номер заказа', status => 'X', name => 'num_order', value => ''),
        array(form => 'date_form', caption => 'Дата начала', format => 'dd.mm.yy', status => 'X', name => 'datetime_begin', value => ($action == 'add' ) ? date("d.m.Y") : ''),
        array(form => 'date_form', caption => 'Дата конца', format => 'dd.mm.yy', status => 'X', name => 'datetime_expire', value => ''),
        array(form => 'select', caption => 'Период', first_val => '', status => 'X', name => 'period_id', value => '2',
            data => array('vars_db::__table', array('table' => 'periods', 'order' => 'id'))),
        array(form => 'select',
            caption => 'Сервера',
            first_val => 'no',
            status => 'X',
            sel_field => 'id, name',
            name => 'order_server_ids', value => array(),
            get_value => array('vars_db::__selected_ids', array('table' => 'order_server_ids', 'field' => 'serverID', 'where' => (($id) ? 'orderID=' . $id : ''))),
            data => array('vars_db::__table', array('table' => 'servers', 'where' => ($action == 'add') ? ' idmultidouble="" and iddouble=""' : ''))),
        array(form => 'select', caption => 'Статус', status => 'X', first_val => 'no', name => 'action_id', value => '',
            data => array('vars_db::__table', array('table' => 'actions', 'order' => 'id'))),
        array(form => 'text', caption => 'Цена($)', status => 'X', name => 'price', value => ''),
        array(form => 'checkbox', caption => 'is Portable', status => '0', name => 'portable', value => 1, checked => 1),
        array(form => 'select_simple', caption => 'OS', status => 'X', name => 'os', value => '', values => array('win' => 'Win', 'mac' => 'Mac')),
        array(form => 'textarea', caption => 'Заметки', status => '0', name => 'notes', value => ''),
//        array(form => 'date_form', caption => 'Дата редакции', status => '', name => 'datetime_edit', value => ''),
//        array(form => 'select', caption => 'Аккаунт', first_val => '', status => '0', disabled=>1,  name => 'account_id', value => '',
//            data=>array('vars_db::__table',array('table'=>'accounts'))),
        array(form => 'hidden', status => '0', name => 'account_id', value => ''),
        ($action == 'copy') ? array(form => 'checkbox', caption => 'Блокировать родительский заказ', status => '0', name => 'is_lock_parent', no_sql => 1, value => 1, checked => 1) : null,
    ),
    user_groups => array(
        array(form => 'text', caption => 'Название', status => 'X', name => 'name', value => ''),
        array(form => 'text', caption => 'Кол-во дней по начала рассылки', status => 'X', name => 'note_period_days', value => ''),
        array(form => 'select_simple', 
            caption => 'Способ рассылки сообщений', status => '0',
            name => 'note_method',
            values => array('email' => 'email', 'jabber' => 'jabber', 'icq' => 'icq'), value =>''),
        array(form => 'select', caption => 'Сообщение', status => 'X', first_val => 'no', name => 'mess_id', value => '',
            data => array('vars_db::__table', array('table' => 'user_messages', 'order' => 'id'))),

    ),
    user_messages => array(
        array(form => 'text', caption => 'Тема', status => 'X', name => 'name', value => ''),
        array(form => 'textarea', caption => 'Сообщение', status => 'X', name => 'mess', value => '', css => 'tinymce'),
    )
);
?>